FROM node:14 AS build

RUN mkdir /app
WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install

FROM node:14-slim

RUN mkdir /app
WORKDIR /app
COPY --from=build /app/node_modules /app/node_modules

COPY ./ ./

ENV NODE_ENV=production

CMD npm start